from __future__ import annotations

import importlib

__all__ = [
    "BaseMemoryHarness",
    "ContextStrategy",
    "ExecutionCheckpointCompatibilityError",
    "ExecutionCheckpointError",
    "ExecutionCheckpointHarness",
    "ExecutionCheckpointIntegrityError",
    "ExecutionCheckpointPersistenceError",
    "ExecutionCheckpointReplayUnavailableError",
    "ExecutionCheckpointResumeRequiredError",
    "FencedRevisionedSessionStore",
    "HybridContextStrategy",
    "InMemorySessionStore",
    "JsonFileLongTermProfileStore",
    "JsonFileSessionStore",
    "KernelMemoryRuntime",
    "LastNTurnsStrategy",
    "LongTermExtractor",
    "LongTermMemoryConfig",
    "LongTermProfileStore",
    "LongTermRecallMemoryHarness",
    "LongTermVectorAdapter",
    "MemoryBootstrapHarness",
    "MemoryCommitEventHarness",
    "MemoryCommitHarness",
    "MemoryCommitResult",
    "MemoryConfig",
    "MemoryContext",
    "MemoryHarness",
    "MemoryManager",
    "MemoryPrepareEventHarness",
    "MEMORY_EFFECT_CREATED_BY_PREFIX",
    "QdrantLongTermVectorAdapter",
    "QdrantVectorAdapter",
    "RevisionedSessionStore",
    "SessionConsistency",
    "SessionHistoryOwnershipError",
    "SessionRevisionConflictError",
    "SessionSnapshot",
    "SessionStore",
    "SessionStoreCorruptionError",
    "ShortTermRecallMemoryHarness",
    "SummaryGenerator",
    "SummaryTokenStrategy",
    "VectorStoreAdapter",
    "build_default_memory_components",
    "build_memory_commit_event",
    "build_memory_delta",
    "build_memory_prepare_event",
    "build_openai_embed_fn",
    "collect_complete_turns_for_vector_index",
    "load_session_snapshot",
    "memory_commit_update",
    "memory_prepare_update",
    "memory_state_update",
    "save_session_snapshot",
]

_EXPORT_TO_MODULE = {
    "build_default_memory_components": ".assembly",
    "LongTermMemoryConfig": ".config",
    "MemoryConfig": ".config",
    "MEMORY_EFFECT_CREATED_BY_PREFIX": ".effects",
    "build_memory_commit_event": ".effects",
    "build_memory_delta": ".effects",
    "build_memory_prepare_event": ".effects",
    "memory_commit_update": ".effects",
    "memory_prepare_update": ".effects",
    "memory_state_update": ".effects",
    "BaseMemoryHarness": ".base",
    "MemoryContext": ".base",
    "MemoryHarness": ".base",
    "MemoryBootstrapHarness": ".bootstrap",
    "ExecutionCheckpointHarness": ".checkpoint",
    "ExecutionCheckpointCompatibilityError": ".checkpoint_state",
    "ExecutionCheckpointError": ".checkpoint_state",
    "ExecutionCheckpointIntegrityError": ".checkpoint_state",
    "ExecutionCheckpointPersistenceError": ".checkpoint_state",
    "ExecutionCheckpointReplayUnavailableError": ".checkpoint_state",
    "ExecutionCheckpointResumeRequiredError": ".checkpoint_state",
    "FencedRevisionedSessionStore": ".stores",
    "MemoryCommitHarness": ".commit",
    "MemoryCommitEventHarness": ".events",
    "MemoryPrepareEventHarness": ".events",
    "collect_complete_turns_for_vector_index": ".indexing",
    "JsonFileLongTermProfileStore": ".long_term",
    "LongTermExtractor": ".long_term",
    "LongTermProfileStore": ".long_term",
    "LongTermVectorAdapter": ".long_term",
    "MemoryManager": ".manager",
    "MemoryCommitResult": ".manager",
    "SummaryGenerator": ".manager",
    "SessionHistoryOwnershipError": ".ownership",
    "JsonFileSessionStore": ".qdrant",
    "QdrantLongTermVectorAdapter": ".qdrant",
    "QdrantVectorAdapter": ".qdrant",
    "build_openai_embed_fn": ".qdrant",
    "LongTermRecallMemoryHarness": ".recall_long_term",
    "KernelMemoryRuntime": ".runtime",
    "ShortTermRecallMemoryHarness": ".short_term",
    "InMemorySessionStore": ".stores",
    "RevisionedSessionStore": ".stores",
    "SessionConsistency": ".stores",
    "SessionRevisionConflictError": ".stores",
    "SessionSnapshot": ".stores",
    "SessionStore": ".stores",
    "SessionStoreCorruptionError": ".stores",
    "VectorStoreAdapter": ".stores",
    "load_session_snapshot": ".stores",
    "save_session_snapshot": ".stores",
    "ContextStrategy": ".strategies",
    "HybridContextStrategy": ".strategies",
    "LastNTurnsStrategy": ".strategies",
    "SummaryTokenStrategy": ".strategies",
}


def __getattr__(name: str):
    module_name = _EXPORT_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(name)
    module = importlib.import_module(module_name, __name__)
    return getattr(module, name)


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
